project_id = "zcgutkfkohonpqvwfukk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.admin-users]
verify_jwt = false

[functions.admin-set-admin]
verify_jwt = false

[functions.stop-email-sequence]
verify_jwt = false

[functions.process-email-replies]
verify_jwt = false

[functions.get-due-email-steps]
verify_jwt = false

[functions.dev-stop-sequence]
verify_jwt = false

[functions.crm-sync]
verify_jwt = true

[functions.vapi-webhook]
verify_jwt = false

[functions.send-gmail]
verify_jwt = false

[functions.retrieve-searchleads-export]
verify_jwt = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true